baseURL = 'http://example.org/'
languageCode = 'en-gb'
title = 'CHipCie'
theme = "ananke"
copyright = "W.I.S.V. `Christiaan Huygens'"

SectionPagesMenu = "main"
Paginate = 5
enableRobotsTXT = true

[params]
  favicon = ""
  site_logo = "/logo/chipcie.svg"
  background_color_class = "bg-navy"
  featured_image = "/images/chipciegroot2.png"
  recent_posts_number = 0
  custom_css = ["archive.css"]
  mainSections = ['news']

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
